import { Noto_Sans } from 'next/font/google';

import { cn } from '@/lib/utils';

import type { Metadata } from 'next';

import '@/app/globals.css';

const NOTO_SANS = Noto_Sans({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(NOTO_SANS.className, 'antialiased')}>{children}</body>
    </html>
  );
}
